language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
before_install:
  - "sudo apt-get install -qq python-numpy cython"
install: 
  - "pip install -e ."
# command to run tests
script: nosetests
